# Description.
model_template_id: Custom_Semantic_Segmentation_Lite-HRNet-18-mod2_OCR
name: Lite-HRNet-18-mod2 OCR
task_type: SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Lightweight architecture which based on the Lite-HRNet backbone with OCR head for the fast inference and training on the limited amount of data.
application:
  ~

# Algo backend.
framework: OTESegmentation v0.14.0

# Task implementations.
entrypoints:
  base: mmseg.apis.ote.apis.segmentation.OTESegmentationTrainingTask
  openvino: mmseg.apis.ote.apis.segmentation.OpenVINOSegmentationTask
  # nncf: mmseg.apis.ote.apis.segmentation.OTESegmentationNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmseg/apis/ote/apis/segmentation/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 8
      learning_rate:
        default_value: 0.001
      learning_rate_fixed_iters:
        default_value: 0
      learning_rate_warmup_iters:
        default_value: 80
      num_iters:
        default_value: 180
    pot_parameters:
      preset:
        default_value: Mixed
      stat_subset_size:
        default_value: 500
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 3.63
size: 4.8
